### ISSUE TITLE
Display possible moves on the board 

### ISSUE THREAD

**Issue by RobStallion** [RobStallion/chess-elm#10]
Displaying the possible moves on the board. 

Idea of what it could look like taken from @nelsonic 's comment in #9 
![chess-board-initial-state](https://user-images.githubusercontent.com/194400/53718490-4279d880-3e53-11e9-8bf0-03db6c3ed092.png)

Decide what action causes possible moves to display
- Do they appear on a mousedown (and disappear on mouseup)?
- Do they appear on mouseclick and stay onscreen until another mouseclick happens?

**Comment by nelsonic** [comment]
@RobStallion as your intuition is suggesting, if you want your game/UI to be mobile first (_or even just mobile "friendly"_), you will need to register the `tap` or `mouseclick` event and activate the the highlight.  see: https://developer.mozilla.org/en-US/docs/Web/API/Touch_events
For desktop (_or anywhere a `long press` or `mousedown` can be tracked_), display the valid moves on that action and hide them on [`mouseleave`](https://developer.mozilla.org/en-US/docs/Web/Events/mouseleave)
I feel this is an (_incredibly_) "nice to have" feature to be considered _much_ later. 🤔 
And if you could display the range of moves by color grading (_brighter highlights are better moves_) it would ["win the internet"](https://www.google.com/search?q=win+the+internet&tbm=isch)!

**Comment by RobStallion** [comment]
> I feel this is an (incredibly) "nice to have" feature to be considered much later. 🤔
And if you could display the range of moves by color grading (brighter highlights are better moves) it would "win the internet"!

@nelsonic I really like this idea (A LOT). I don't want to forget it so I am going to put it into it's own issue and label as a stretch (or something along those lines). Thanks 👍

**Comment by RobStallion** [comment]
I have managed to get this working (as an onClick event for the time being). It is a little ugly right now but it is showing that it is working as expected...

![image](https://user-images.githubusercontent.com/15571853/53910018-c8ac3f80-404a-11e9-86aa-7ea049df19b2.png)

**Comment by RobStallion** [comment]
Didn't account for a case where someone changes their mind...

![image](https://user-images.githubusercontent.com/15571853/53910499-e332e880-404b-11e9-849a-350dd95cfb71.png)

**Comment by nelsonic** [comment]
@RobStallion indeed. clicking a different piece should reset the available moves highlight for the _previous_ piece. 😉 
Looking good so far. 👍
