### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by RobStallion** [RobStallion/chess-elm#2]
- [x] Include instructions on how to start the app
- [x] Say why you are building it

| Edits | View issue history |
|-|-|
|[![Edit Count](http://localhost:4000/edit-count/388144218)](http://localhost:4000/edit-count/388144218) | **View History:** [http://localhost:4000/issues/388144218](http://localhost:4000/issues/388144218)|

**Comment by RobStallion** [comment]
This is what is looks like in master at this point in time...

![image](https://user-images.githubusercontent.com/15571853/53729657-add0a400-3e6d-11e9-9416-09eb85d1b294.png)

**Comment by nelsonic** [comment]
@RobStallion very interesting! 👍 
When you next work on this, I look forward to understanding the context of the 10x10 matrix. 🤔

**Comment by RobStallion** [comment]
@nelsonic Ahhh so feel free to ask me as much as you want about that and anything else for that matter but this particular point was one I really thought about before I started the project and just found interesting in general.

So the reason I decided to go with a 10*10 board was to help with move logic. It seemed like a sensible way to resolve the possible issues that could come up with pieces moving in patterns that they shouldn't.

For example, I didn't want behaviour like this....
<img width="581" alt="screenshot 2019-03-04 at 17 40 45" src="https://user-images.githubusercontent.com/15571853/53752114-b04ef000-3ea5-11e9-846c-735de3de3b81.png">

Where a bishop could move onto a different diagonal. So the boarder acts as an out of bounds zone. If a piece hits a number in the out of bounds list then it can not move any further. 

This could also be achieved with a 9*9 board but then that doesn't account for knight moves. 
![image](https://user-images.githubusercontent.com/15571853/53752531-b98c8c80-3ea6-11e9-8a0f-6af7c1cc775b.png)
Take my knight on A3. Knights (as you know) move in an L shape. If this tried to move up one tile and left 2 tiles it would end up on index 40. If the board only didn't have 2 out of bounds tiles in a row the knight would be able to make crazy moves. 

Of course this is only a problem for me as I am working out all the piece moves by with simple addition and subtraction, for example, a rook can move in indexes of +/-10 & +/- 1. 

I'm sure that there are plenty of other ways that this problem could be approached and solved but this seemed like the most logical to me.

**Comment by nelsonic** [comment]
@RobStallion thanks for the explanation. I would _love_ to see your _paper_ notes on this! 😉

**Comment by RobStallion** [comment]
@nelsonic I think that I still have them so I'll have a look and post them here if I do 👍

**Comment by RobStallion** [comment]
@nelsonic These are the notes I had for this...
[board-notes.zip](https://github.com/RobStallion/chess-elm/files/2975579/board-notes.zip)

**Comment by RobStallion** [comment]
@nelsonic. I just realised I could (and should) have just posted the actual images 😑 

Sorry. Obviously wasn't thinking. 

Here they are...

![IMG_20190317_184439](https://user-images.githubusercontent.com/15571853/54497794-ca9dba80-48f6-11e9-9194-53150f026e83.jpg)
![IMG_20190317_184445](https://user-images.githubusercontent.com/15571853/54497795-cd001480-48f6-11e9-995c-6b24cc513bde.jpg)

**Comment by nelsonic** [comment]
@RobStallion nice!
