### ISSUE TITLE
Track previous move

### ISSUE THREAD

**Issue by RobStallion** [RobStallion/chess-elm#29]
Keep track of the previous move. 

## Acceptance Criteria
- [x] Add previousMove to the model
- [x] Have previousMove take a tuple of Piece, previousIndex and newIndex.

Relates to #26

**Comment by RobStallion** [comment]
I have seen a notation before for tracking the state of a chess board but I cannot remember what it was called. It was a long string that had to position of every piece on the board. 

Will look into this as a way of storing game state but it is not urgent. Just thought it could be a nice to have in the future.

@nelsonic if you know the name of my poor description then please comment 😂 👍

**Comment by nelsonic** [comment]
@RobStallion GOTO: #18 where Forsyth–Edwards Notation (FEN) is mentioned. 😉 
But you may also be interested in "PGN": https://en.wikipedia.org/wiki/Portable_Game_Notation if you want to parse an existing database of games. 💭

**Comment by RobStallion** [comment]
Thanks @nelsonic. You're **WAY** ahead of me 😄

**Comment by nelsonic** [comment]
@RobStallion I'm not "ahead", I'm just super curious about all this. 💡
