### ISSUE TITLE
club soda testing

### ISSUE THREAD

**Issue by RobStallion** [RobStallion/chess-elm#5]
putting this issue here as I didn't want to clutter the cs repo. Can copy over afterwards if needed

**Comment by RobStallion** [comment]
changing the db from my local copy to prod copy. Using copy of prod from 4 hours ago today

**Comment by RobStallion** [comment]
https://github.com/club-soda/club-soda-guide/pull/358 this was the last commit merged into master when I started testing.

Ran the following on the latest prod db copy. 
```
club-soda-guide git:(master) ✗ mix ecto.migrate
[info] Already up
```

Good start

**Comment by RobStallion** [comment]
going to try and follow the router so that I don't miss any endpoints 

### passed

#### scope /
- /     search bar and use my location work.
- /brands/Double-Dutch-Drinks
- /drinks
  - `resources("/drinks", DrinkController, only: [:show])` not sure how to get to this route.
  - tried drink/id and drink/entry_id. 
  - got sent link which seems to work `/drinks/749a0267-381d-4134-934a-cd2ca0c2a2ff`
- /users/new (kind of pass. submits to signup which is erroring. This page is fine though)
- /users [create] 
- /venues/:slug 
- /sessions [new/create both fine]
- / json_drinks 

#### scope /search

- /drinks 
  - drinks display fine. filter by abv works. drink type filter also seems to work. Also links on back of cards. (no images but that should happen)
  - /venues both filters working and links work (no images but should be good)
  - /venue/all




### failed 
/signup [create] 
failing because the slug is not being created for this endpoint...
```elixir
#Ecto.Changeset<
  action: nil,
  changes: %{},
  errors: [
    venue_name: {"can't be blank", [validation: :required]},
    postcode: {"can't be blank", [validation: :required]},
    slug: {"can't be blank", [validation: :required]}
  ],
  data: #CsGuide.Resources.Venue<>,
  valid?: false
>
```
@simonLab is aware and is fixing this

**Comment by RobStallion** [comment]
### working

#### score /admin
/ and all the index pages from / work

**Comment by RobStallion** [comment]
Trying to upload an image to a venue but it is not appearing at the moment

**Comment by RobStallion** [comment]
It's fine. Image comes from s3

**Comment by nelsonic** [comment]
@robstallion this kind of testing walkthrough is absolutely worth having in the main project! Please put it in /test/README.md 👍🏻
