### ISSUE TITLE
Focus on UI (What People See)

### ISSUE THREAD

**Issue by nelsonic** [RobStallion/chess-elm#9]
@RobStallion I'm _really_ excited to see the progress on this project and feel that it's a _really_ good showcase of both your Elm and critical reasoning skills! I would add it to your CV as a "spare time learning" project. Hiring/Engineering/HR Managers want to see that you are learning new skills in your _own_ time not just "on the clock" ... it's a _massive_ differentiator between you and your less _proactive_ peers. 

At present a person viewing your GH profile, sees only one thing:
![image](https://user-images.githubusercontent.com/194400/53717984-d054c400-3e51-11e9-9a9c-91c2baca6106.png)

But when they click to view the repo, it's kinda bare: https://github.com/RobStallion/chess-elm
![image](https://user-images.githubusercontent.com/194400/53718094-27f32f80-3e52-11e9-8d5b-db53b32f32a3.png)

If it is your _only_ showcased repo on your profile, I would _highly_ recommend that you `make` it a _showcase_ of your skills. You touched upon this fact in https://github.com/RobStallion/chess-elm/issues/2 but have instead dived into figuring out the Pawn moving algo. (_I can see the appeal of diving into solving one of the challenges rather than documenting it ... but you **must** demonstrate **Document-Driven Development** if you want to show that skill to an observer..._)

You don't need to _have_ a fully formed UI, you can _borrow_ one from https://chessui.com 
![image](https://user-images.githubusercontent.com/194400/53717847-5ae8f380-3e51-11e9-8af2-8dfd557864f2.png)

Just having a chess board in your readme is a night-and-day difference from a _blank_ one. 

And with a bit of photoshop ("_smoke and mirrors_") you can illustrate the issue #1 you are _currently_ working on; "available moves for king's pawn on home square with no obstructions":
![chess-board-initial-state](https://user-images.githubusercontent.com/194400/53718490-4279d880-3e53-11e9-8bf0-03db6c3ed092.png)
 
Ultimately "as a reader" of our GH profile I want to be "wowed" by what you've been working on. 😉

**Comment by RobStallion** [comment]
@nelsonic Can this issue be closed now?

**Comment by nelsonic** [comment]
@RobStallion Yes, I think we can close this issue because it is not _specific_ enough.
We need an issue that is clearer on _exactly_ what UI/UX needs to be.
For example when a piece can move to a square where another pieces currently is (_i.e. a "capture"_),
how is that UI represented? This is worth having a separate (_new_) issue. 👍

**Comment by RobStallion** [comment]
Thanks a lot for the advice/thoughts on this @nelsonic. I really appreciate it 👍 👍 👍 

Also did you see [this](https://github.com/RobStallion/chess-elm/commit/a0be7d4bed99e5c108cd57a160b066805ab6e466). Thought it would help make the readme a little more exciting
